version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  elasticsearch:
    image: elasticsearch:7.12.1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
  
  kibana:
    image: kibana:7.12.1
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
      
  redis:
    image: redis:latest
    ports:
      - 6379:6379
      
  basket:
    image: x-basket-service:1.0
    depends_on:
      - elasticsearch
    ports:
      - 44308:80
      
  payment:
    image: x-payment-service:1.0
    depends_on:
      - elasticsearch
    ports:
      - 59333:80
      
  tournament:
    image: x-tournament-service:1.0
    depends_on:
      - elasticsearch
    ports:
      - 51000:80
      
  player:
    image: x-player-service:1.0
    depends_on:
      - elasticsearch
    ports:
      - 44322:80
      
volumes:
  data01:
    driver: local